version: "3.8"

services:
    mongodb:
        image: mongo:latest
        container_name: kubercode-sso-mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s

    redis:
        image: redis:latest
        container_name: kubercode-sso-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s

    nats:
        image: nats:latest
        container_name: kubercode-sso-nats
        ports:
            - "4222:4222"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4222/healthz"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    mongodb_data:
    redis_data:
